# Generated by Django 3.2.16 on 2025-02-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20250223_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(class)ss', 'ordering': ('-pub_date',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
